// Bundled sample data used ONLY as a fallback when the real backend is unreachable
// (network error / backend not started yet). This keeps Home -> Discovery -> Storefront
// browsable during frontend development without blocking on the backend team.
// It is never used once the API responds (even with an empty list).
import type { Store } from './stores'
import type { Product } from './products'

export const FIXTURE_STORES: Store[] = [
  {
    id: 'store-green-valley',
    name: 'Green Valley Supermarket',
    logoUrl: undefined,
    rating: 4.6,
    ratingCount: 812,
    distanceKm: 0.8,
    etaMinutes: 22,
    isOpen: true,
    address: '12 MG Road',
    categories: ['Groceries', 'Fresh Produce', 'Dairy'],
  },
  {
    id: 'store-daily-basket',
    name: 'Daily Basket',
    logoUrl: undefined,
    rating: 4.3,
    ratingCount: 431,
    distanceKm: 1.4,
    etaMinutes: 28,
    isOpen: true,
    address: '45 Lake View Street',
    categories: ['Groceries', 'Snacks', 'Beverages'],
  },
  {
    id: 'store-city-mart',
    name: 'City Mart',
    logoUrl: undefined,
    rating: 4.1,
    ratingCount: 265,
    distanceKm: 2.1,
    etaMinutes: 35,
    isOpen: false,
    address: '9 Station Road',
    categories: ['Groceries', 'Household'],
  },
]

export const FIXTURE_PRODUCTS: Product[] = [
  {
    id: 'prod-milk-1l',
    storeId: 'store-green-valley',
    name: 'Toned Milk 1L',
    description: 'Fresh toned milk, pasteurized daily.',
    imageUrl: undefined,
    price: 58,
    mrp: 62,
    unit: '1 L',
    category: 'Dairy',
    inStock: true,
    stockQuantity: 40,
  },
  {
    id: 'prod-bread-1',
    storeId: 'store-green-valley',
    name: 'Whole Wheat Bread',
    description: 'Soft whole-wheat sandwich bread.',
    imageUrl: undefined,
    price: 45,
    mrp: 48,
    unit: '400 g',
    category: 'Bakery',
    inStock: true,
    stockQuantity: 15,
  },
  {
    id: 'prod-tomato-1',
    storeId: 'store-green-valley',
    name: 'Tomato',
    description: 'Farm-fresh red tomatoes.',
    imageUrl: undefined,
    price: 32,
    unit: '1 kg',
    category: 'Fresh Produce',
    inStock: true,
    stockQuantity: 60,
  },
  {
    id: 'prod-rice-5kg',
    storeId: 'store-green-valley',
    name: 'Basmati Rice',
    description: 'Premium long-grain basmati rice.',
    imageUrl: undefined,
    price: 420,
    mrp: 460,
    unit: '5 kg',
    category: 'Groceries',
    inStock: false,
    stockQuantity: 0,
  },
  {
    id: 'prod-chips-1',
    storeId: 'store-daily-basket',
    name: 'Salted Potato Chips',
    description: 'Crispy salted potato chips.',
    imageUrl: undefined,
    price: 20,
    unit: '52 g',
    category: 'Snacks',
    inStock: true,
    stockQuantity: 100,
  },
  {
    id: 'prod-cola-1',
    storeId: 'store-daily-basket',
    name: 'Cola 750ml',
    description: 'Chilled soft drink.',
    imageUrl: undefined,
    price: 40,
    unit: '750 ml',
    category: 'Beverages',
    inStock: true,
    stockQuantity: 50,
  },
]
